Exercise 1. Import numpy as np and see the version

In [1]:
import numpy as np
print(np.__version__)

2.2.6


Exercise 2. How to create a 1D array?

In [2]:
# Question : Create a 1D array of numbers from 0 to 9
# Output : #> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution
X = np.arange(10)
X

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Exercise 3. How to create a boolean array?

In [3]:
# Question : Create a 3×3 numpy array of all True’s

# Solution
np.full((3,3), True, dtype=bool)

#or
np.full((9), True, dtype=bool).reshape(3,3)

#or
np.ones((3,3), dtype=bool)

#or
np.ones((9), dtype=bool).reshape(3,3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Exercise 4. How to extract items that satisfy a given condition from 1D array?

In [4]:
# Question : Extract all odd numbers from array
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([1, 3, 5, 7, 9])

#Solution

arr = np.arange(10)

arr[arr%2 == 1]

array([1, 3, 5, 7, 9])

Exercise 5. How to replace items that satisfy a condition with another value in numpy array?

In [5]:
# Question: Replace all odd numbers in arr with -1
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# Solution

arr = np.arange(10)

arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Exercise 6. How to replace items that satisfy a condition without affecting the original array?¶



In [7]:
# Question: Replace all odd numbers in arr with -1 without changing arr
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: out
# array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
# arr
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution

arr = np.arange(10)

out = arr.copy()

out[out%2 == 1] = -1

print('Modified Array',out)


print('\nOriginal Array',arr)


Modified Array [ 0 -1  2 -1  4 -1  6 -1  8 -1]

Original Array [0 1 2 3 4 5 6 7 8 9]
