Exercise 1. Import numpy as np and see the version

In [1]:
import numpy as np
print(np.__version__)

2.2.6


Exercise 2. How to create a 1D array?

In [2]:
# Question : Create a 1D array of numbers from 0 to 9
# Output : #> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution
X = np.arange(10)
X

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Exercise 3. How to create a boolean array?

In [3]:
# Question : Create a 3×3 numpy array of all True’s

# Solution
np.full((3,3), True, dtype=bool)

#or
np.full((9), True, dtype=bool).reshape(3,3)

#or
np.ones((3,3), dtype=bool)

#or
np.ones((9), dtype=bool).reshape(3,3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Exercise 4. How to extract items that satisfy a given condition from 1D array?

In [4]:
# Question : Extract all odd numbers from array
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([1, 3, 5, 7, 9])

#Solution

arr = np.arange(10)

arr[arr%2 == 1]

array([1, 3, 5, 7, 9])

Exercise 5. How to replace items that satisfy a condition with another value in numpy array?

In [5]:
# Question: Replace all odd numbers in arr with -1
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# Solution

arr = np.arange(10)

arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Exercise 6. How to replace items that satisfy a condition without affecting the original array?¶



In [7]:
# Question: Replace all odd numbers in arr with -1 without changing arr
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: out
# array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
# arr
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution

arr = np.arange(10)

out = arr.copy()

out[out%2 == 1] = -1

print('Modified Array',out)


print('\nOriginal Array',arr)


Modified Array [ 0 -1  2 -1  4 -1  6 -1  8 -1]

Original Array [0 1 2 3 4 5 6 7 8 9]


Exercise 7. How to reshape an array?

In [17]:
# Question: Convert a 1D array to a 2D array with 2 rows
# input: np.arange(10)
# output array([[0, 1, 2, 3, 4],
#               [5, 6, 7, 8, 9]])

# Solution

arr = np.arange(10)

arr.reshape(2, 5)


# Another solution
arr = np.arange(10)
arr.reshape(2, -1)  # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Exercise 8. How to stack two arrays vertically?

In [19]:
# Question: Stack arrays a and b vertically
# input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)

# output: array([[0, 1, 2, 3, 4],
#                [5, 6, 7, 8, 9],
#                [1, 1, 1, 1, 1],
#                [1, 1, 1, 1, 1]])

# Solution

a = np.arange(10).reshape(2,5)
print('Array a:\n',a)
b = np.repeat(1, 10).reshape(2,5)
print('Array b:\n',b)

np.vstack([a,b])

Array a:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Array b:
 [[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Exercise 9. How to stack two arrays horizontally?

In [21]:
# Question: Stack the arrays a and b horizontally.

# Input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)
# Output: array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#                [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])


# Solution:
a = np.arange(10).reshape(2,-1)
print('Array a:\n',a)
b = np.repeat(1, 10).reshape(2,-1)
print('Array b:\n',b)

np.hstack([a,b])

Array a:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Array b:
 [[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

Exercise 10. How to generate custom sequences in numpy without hardcoding?

In [ ]:
# Question: Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])


# Solution

a = np.array([1,2,3])
print('Array a:\n',a)
#here r_ used to concatenate two arrays 
np.r_[np.repeat(a, 3), np.tile(a, 3)]

#other solution
np.hstack((np.repeat(a, 3), np.tile(a, 3)))

Array a:
 [1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Exercise 11. How to get the common items between two python numpy arrays?

In [24]:
# Question: Get the common items between a and b

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

# Output: array([2, 4])


# Solution:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

Exercise 12. How to remove from one array those items that exist in another?

In [27]:
# Question: From array a remove all items present in array b

# Input: a = np.array([1,2,3,4,5])
#        b = np.array([5,6,7,8,9])

# Output: array([1,2,3,4])


# Solution
a = np.array([1,2,3,4,5,6])
b = np.array([4,5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3])

Exercise 13. How to get the positions where elements of two arrays match?

In [31]:
# Question: Get the positions where elements of a and b match

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

# Output: (array([1, 3, 5, 7]),)


# Solution

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

#here return tuple of arrays (one for each dimension) 
# containing the indices of the elements that are non-zero (or true) 
# in the boolean array resulting from the comparison a == b
print('Array a:\n',a)
print('Array b:\n',b)

print (' positions where elements of a and b match ',np.where(a == b))

#we wil get array indices where both arrays have same values
# [1, 3, 5, 7] 
#to show the values at these indices

a[np.where(a == b)]  
print('\nValues at matching positions in array a:\n',a[np.where(a == b)])
#or 
b[np.where(a == b)]    
print('\nValues at matching positions in array b:\n',b[np.where(a == b)])

Array a:
 [1 2 3 2 3 4 3 4 5 6]
Array b:
 [ 7  2 10  2  7  4  9  4  9  8]
 positions where elements of a and b match  (array([1, 3, 5, 7]),)

Values at matching positions in array a:
 [2 2 4 4]

Values at matching positions in array b:
 [2 2 4 4]


Exercise 14. How to extract all numbers between a given range from a numpy array?

In [32]:
# Question: Get all items between 5 and 10 from a.

# Input: a = np.array([2, 6, 1, 9, 10, 3, 27])
# Output: (array([6, 9, 10]),)


# Solution

a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

Exercise 15. How to make a python function that handles scalars to work on numpy arrays?

In [33]:
# Question: Convert the function maxx that works on two scalars, to work on two arrays.
# Input:

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

# maxx(1, 5)
#> 5

# Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

# Solution

def pair_max(x, y):
    # here I am using map to make tuple from a and b, other solution is using zip(a,b)
    maximum = [maxx(a,b) for a,b in map(lambda a,b:(a,b),x,y)]
    # using zip
    # maximum = [maxx(a,b) for a,b in zip(x,y)]
    return np.array(maximum)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])